### ISSUE TITLE
database: create query to return drinks by given ingredients

### ISSUE THREAD

**Issue by e56** [VesperApp/VesperApp#9]
// TODO: POST: return drinks by given ingredients
app.post('/drinks', (req, res) => {});

**Comment by juliofihdeldev** [comment]
Waiting to test and implement the algorithm for match strIngredient in mongod by @PotatoEater0127

**Comment by PotatoEater0127** [comment]
Do I pull it from upstream and test? @juliofihdeldev

**Comment by juliofihdeldev** [comment]
No sorry i mean   @e56  to test the endpoint and implement the algorithm for match strIngredient
